name: flutter_link_preview
description: This is a URL preview plugin that previews the content of a URL.
version: 1.5.6
homepage: https://github.com/yungzhu/flutter_link_preview

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
        
    collection: ^1.15.0-nullsafety.4
    html: ^0.15.0
    http: ^0.13.3